=== VijayEluri/Toobs-1/trunk/PresFramework/src/main/castor/componentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by spudney (private) -->
<xs:schema targetNamespace="http://www.toobsframework.org/schema/component" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cc="http://www.toobsframework.org/schema/component" elementFormDefault="qualified"
           attributeFormDefault="unqualified">
 <xs:element name="Components">
  <xs:annotation>
   <xs:documentation>
   This configuration describes multiple components, usually inside a .cc.xml file
   Inside of Components, multiple Component (zero or many) elements can be located
   </xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Component" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="Component">
  <xs:annotation>
   <xs:documentation>
    This element holds the component definition.  It is composed by multiple Style elements,
    Controller elements, GetObject elements and one Pipeline element.
    
    Each component needs to be identified by a unique id attribute
    The attributes are as follows:
    renderErrorObject (true/false) - to show ...
   </xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Style" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="cc:Controller" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="cc:GetObject" maxOccurs="unbounded" minOccurs="0"/>
    <xs:element ref="cc:Pipeline"/>
   </xs:sequence>
   <xs:attribute name="id" type="xs:string" use="required"/>
   <xs:attribute name="renderErrorObject" type="xs:boolean" default="false"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="DataProviderProperty">
  <xs:annotation>
   <xs:documentation>This element holds a DataProvider property, which is composed of a DataProviderPropertyName,
    followed by multiple DataProviderPropertyVaue elements</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element name="DataProviderPropertyName" type="xs:string"/>
    <xs:element name="DataProviderPropertyValue" type="xs:string" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="ContentType">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Transform" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="contentType" type="xs:string" default="xhtml"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="Pipeline">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:ContentType" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="Transform">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Parameters" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="type" type="xs:string" use="optional" default="xsl"/>
    <xs:attribute name="moment" default="normal">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="normal"/>
          <xs:enumeration value="pre"/>
          <xs:enumeration value="post"/>
        </xs:restriction>
      </xs:simpleType>        
    </xs:attribute> 
  </xs:complexType>
 </xs:element>
 <xs:element name="GetObject">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Parameters" minOccurs="0"/>
    <xs:element ref="cc:OutputParameters" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="action" use="required" type="xs:string"/>
   <xs:attribute name="serviceProvider" use="optional" type="xs:string" default="" />
   <xs:attribute name="property" use="optional" type="xs:string" default="" />
   <xs:attribute name="returnedValueObject" use="optional" type="xs:string"/>
   <xs:attribute name="guidParam" type="xs:string"/>
   <xs:attribute name="searchCriteria" type="xs:string"/>
   <xs:attribute name="searchMethod" type="xs:string"/>
   <xs:attribute name="permissionAction" type="xs:string"/>
   <xs:attribute name="noCache" type="xs:boolean" default="false"/>
   <xs:attribute name="extended" type="xs:boolean" default="false"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="Parameters">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="cc:Parameter" minOccurs="1" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="OutputParameters">
   <xs:complexType>
     <xs:sequence>
       <xs:element ref="cc:Parameter" minOccurs="1" maxOccurs="unbounded"/>
     </xs:sequence>
   </xs:complexType>
 </xs:element>
 <xs:element name="Parameter">
  <xs:complexType>
   <xs:sequence>
     <xs:element ref="cc:JexlExpression" minOccurs="0"/>
     <xs:element ref="cc:JexlScript" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="path" type="xs:string" use="required"/>
   <xs:attribute name="sessionPath" type="xs:string" use="optional"/>
   <xs:attribute name="default" type="xs:string" use="optional"/>
   <xs:attribute name="condition" type="xs:string" use="optional"/>
   <xs:attribute name="scope" type="xs:string" use="optional"/>
   <xs:attribute name="isStatic" type="xs:boolean" default="false"/>
   <xs:attribute name="isObject" type="xs:boolean" default="false"/>
   <xs:attribute name="isList" type="xs:boolean" default="false"/>
   <xs:attribute name="ignoreNull" type="xs:boolean" default="false"/>
   <xs:attribute name="overwriteExisting" type="xs:boolean" default="true"/>
   <xs:attribute name="objectIndex" type="xs:int" default="0"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="Controller">
  <xs:complexType>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
  <xs:element name="Style">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="JexlExpression" type="xs:string"/>
  <xs:element name="JexlScript" type="xs:string"/>

</xs:schema>

=== VijayEluri/Toobs-1/trunk/web/src/main/resources/cc/example.cc.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns="cc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="cc
  file:../../../../../PresFramework/src/main/castor/componentConfig.xsd">

  <Component id="">
    <GetObject objectAction="" daoObject="" searchCriteria="" searchMethod="" returnedValueObject="" permissionAction="">
      <Parameters>
        <Parameter name="" path="" default=""/>
      </Parameters>
    </GetObject>
    <Pipeline>
      <ContentType>
        <Transform name="">
          <Parameters>
            <Parameter name="" path=""></Parameter>
          </Parameters>
        </Transform>
      </ContentType>
    </Pipeline>
  </Component>
</Components>
